version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "sua-maeEuOdeioReact2x"
      MSSQL_PID: "Express"
      MSSQL_TCP_PORT: "1433"
      MSSQL_DATABASE: "sua-mae"
    ports:
      - "1433:1433"
